### ISSUE TITLE
Cannot install csvigo

### ISSUE THREAD

**Issue by shervinf66** [clementfarabet/lua---csv#11]
I have tried to install csvigo by "sudo luarocks install csvigo" however I received the below error:
 Error: No results matching query were found.

Please let me know how I can fix this.
Thanks

**Comment by soumith** [comment]
you do not need sudo. It's also unclear what your luarocks is pointing to.

giving info on:

which luarocks

will help

**Comment by shervinf66** [comment]
If I do not use sudo then I receive permission denied error.
if I execute which luarocks I get:
/opt/torch/install/bin/luarocks

**Comment by shervinf66** [comment]
I even search the website luarocks.org for the package csvigo and I could not find the package in the root manifest. Maybe that is why it cannot install csvigo with out specifying any manifest besides the default one(root).
I am really new to torch and lua so I really appreciate it if you can explain the reasons for problem that I am facing.

**Comment by shervinf66** [comment]
I figured out the problem. actually your point that i should not need sudo was the good clue. thanks you very much. :+1:

**Comment by Saadiabatool** [comment]
/home/usr/torch/install/bin/luarocks
but still facing this issue:

/torch/install/share/lua/5.2/trepl/init.lua:389: module 'csvigo' not found:No LuaRocks module found for csvigo


please help

**Comment by leonardus** [comment]
I solved this by clearing my luarocks cache:
`rm -rf ~/.cache/luarocks`
Luarocks was able to locate the package after this.
