### ISSUE TITLE
Csvigo skipping last CSV line

### ISSUE THREAD

**Issue by AlexMili** [clementfarabet/lua---csv#12]
When I read the following CSV the last line is never read :
```
feature1,feature2,feature3,0
1,2,3,6
4,5,6,7
```
When I add an empty line to the file, all lines are read :
```
feature1,feature2,feature3,0
1,2,3,6
4,5,6,7

```
This is due to the regex used in the function `readall()`

According to [RFC 4180](https://tools.ietf.org/html/rfc4180) "The last record in the file may or may not have an ending line break."

**Comment by soumith** [comment]
thanks for reporting @AlexMili . fixed in trunk.
