### ISSUE TITLE
Last column name improperly contains CR

### ISSUE THREAD

**Issue by Alex870** [clementfarabet/lua---csv#14]
When loading a csv file, the name of the last column contains a carriage return (ASCII 13).

Example of a two column data set with columns named "Input" and "Result" with 98 data rows: 
{["Input"] = sequence[98],["Result**\13**"] = sequence[98]}

This results in queries to correct column name returning no data.

The expected behavior for the previous example would be:
{["Input"] = sequence[98],["Result"] = sequence[98]}

**Comment by soumith** [comment]
you could preprocess your csv with dos2unix, but you make a valid point. let me see how i can quickly fix this.

**Comment by soumith** [comment]
fixed in trunk via commit: https://github.com/clementfarabet/lua---csv/commit/98e565ad89a3d8a6bc61b4962be3207dc74641be
