### ISSUE TITLE
csvigo unreachable through torch

### ISSUE THREAD

**Issue by ThorJonsson** [clementfarabet/lua---csv#16]
I've installed csvigo via luarocks. However when I try to call it in Torch7 I get the following error:

help(csvigo.save)
[string "_RESULT={help(csvigo.save)}"]:1: attempt to index global 'csvigo' (a nil value)
stack traceback:
        [string "_RESULT={help(csvigo.save)}"]:1: in main chunk
        [C]: in function 'xpcall'
        /home/torch/install/share/lua/5.1/trepl/init.lua:645: in function 'repl'
        .../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
        [C]: at 0x00406d30

**Comment by soumith** [comment]
did you do this first:

require 'csvigo'

**Comment by ThorJonsson** [comment]
Worked! Thanks a lot. 

I get undocumented symbol when running help(csvigo.save) or help(csvigo.load). Is this still work in progress or could it be that I did something wrong?

**Comment by soumith** [comment]
try with empty arguments, it should print out the help:

csvigo.load()

**Comment by ThorJonsson** [comment]
Thanks a lot!
